# Generated by Django 4.2.2 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeName', models.CharField(max_length=200)),
                ('SendTo', models.CharField(blank=True, default='+255746244743', max_length=14, null=True)),
                ('NoticeDescription', models.TextField(blank=True, max_length=10000, null=True)),
                ('NoticeImage', models.ImageField(blank=True, null=True, upload_to='media/NewsImage/')),
                ('NoticeDate', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
